# Generated by Django 4.2 on 2026-01-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediconnect_app', '0002_alter_medication_options_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
